### ISSUE TITLE
Falha ao carregar integração

### ISSUE THREAD

**Issue by maxmanager** [hudsonbrendon/HA-ingresso.com#14]
Após a atualização para o HA 2023.6 a integração parou de funcionar. Recebo o seguinte erro no LOG:

ERROR (MainThread) [homeassistant.components.sensor] The ingresso platform for the sensor integration does not support platform setup. Please remove it from your config.

Poderia verificar por gentileza?

**Comment by hudsonbrendon** [comment]
@maxmanager Consegue me passar a configuração que você usa? id da cidade, nome do cinema, etc?
