### ISSUE TITLE
Carregamento dos filmes não acontece no lovelace

### ISSUE THREAD

**Issue by WenderGalan** [hudsonbrendon/HA-ingresso.com#6]
Amigo percebi que tem um problema na integração, as vezes do nada para de carregar o card com os filmes da integração, estou quase removendo porque vira e mexe simplesmente para o carregamento das informações.

![image](https://user-images.githubusercontent.com/30455044/147235066-70545787-130e-49da-b23e-dcc32d375199.png)

**Comment by hudsonbrendon** [comment]
Por aqui ainda não notei esse comportamento, tem funcionado bem pra mim. Essa indisponibilidade pode ser com a API do ingresso.com, pode está passando por alguns problemas em alguns momentos.

**Comment by tibjunior** [comment]
Platform error notify.ingresso - No module named ‘custom_components.ingresso.notify’

ja viu esse erro? carreguei certinho.. mas da isso
